shell = "/bin/bash"

import = [
    "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[font]
size = 12

[font.offset]
y = 1
x = 1

[font.normal]
family = "Iosevka Fixed Medium"
# family = "Monoid"

[window]
startup_mode = "Maximized"
opacity = 0.95

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
