[font]
size = 11

[font.offset]
y = 1
x = 1

[font.normal]
family = "Iosevka Term Medium Extended"

[window]
startup_mode = "Maximized"
opacity = 0.92

[general]

import = [
    "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[terminal]
shell = "/bin/bash"
